ONSdigital/dp-net

- http/client.go
The default retries limit was 10 which is very high for a library used
for internal retires. This is basically causing friendly fire DDoS
issues an resulting in a very poor user experience as it takes ages to
fail. Reducing the default means that we should fail faster, but still
allows for a small failure tolerance.
Anyone but me.
> Decrease default retries to fail faster

- go.mod
- go.sum
Upgrade to log.go 1.0.1
- for use of dp-net context key
Review changes
Anyone
> Upgrade to log.go 1.0.1

- http/utils.go
- http/utils_test.go
Moved `DrainBody` function from go-ns to dp-net/http. This function is used by dp-api-router
- Make sure code changes make sense (function copied from go-ns/request)
- Note: this was added to http package - if we added it to request package, we would reintroduce the cyclic dependency with log.go
- Unit tests should pass
Anyone
> Copied DrainBody function from go-ns to dp-net/http

- handlers/handlers.go
- handlers/handlers_test.go
- handlers/identity.go
- handlers/identity_test.go
- request/collection.go
- request/collection_test.go
- request/locale.go
- request/locale_test.go
A new middleware handler has been added for frontend controller usage.
This middleware ensures that language is always set (defaults if not set) and will log warnings if Florence Access Tokens or Collection IDs are not present.
This can be seen working here: https://github.com/ONSdigital/dp-frontend-homepage-controller/pull/43 on the homepage controller. Note that the PR is failing due to the need of this dp-net PR needing to be pulled into develep, which will happen once this is approved.
Check the tests give full coverage to new code. Ensure that this won't break anything
1. From an app create an implementation of ControllerHandlerFunc.
2. Call ControllerHandler passing in the implementation of ControllerHandlerFunc
3. Magic to occur
4. Note how localeCode, Florence Access token and …
> New controller middleware handler

- request/patch.go
- request/patch_test.go
- Created generic patch operation struct and validation, according to [RFC6902](https://tools.ietf.org/html/rfc6902),
except for the following:
- Value is assumed to be always a list of strings
- Validation accepts a list of supported ops for a particular patch
- Make sure code changes make sense
- Make sure unit tests pass
Anyone
> Added patch struct and validation

- http/server.go
- http/server_test.go
- request/patch.go
- request/patch_test.go
Make `PATCH` value a generic interface{} so that it is not restricted to be always a `[]string`. The caller will need to validate it.
- Make sure that the change make sense
- Make sure unit test pass
Anyone
> Made patch value a generic interface{}

- README.md
- go.mod
- go.sum
- handlers/README.md
- handlers/authentication.go
- handlers/authentication_test.go
- handlers/handlers.go
- handlers/handlers_test.go
- handlers/identity.go
- handlers/identity_test.go
- handlers/mapping.go
- handlers/response/writer_test.go
- handlers/reverseproxy/reverseproxy.go
- handlers/reverseproxy/reverseproxy_test.go
- http/client.go
- http/client_test.go
- http/server.go
The reverseProxy wrapper now allows a modifyResponse function to be sent to the underlining reverseProxy. This is needed so Florence server-side can set secure httpOnly cookies based on the response headers from other services that it proxies to.
This is a breaking change as it changes the reverseProxy Create function signature. As such the module has been bumped to a major new release v2
Go modules upgraded to 1.16 as part of this
Anyone except me
> reverseProxy can now make use of modify response

- http/client.go
- http/custom_roundtripper.go
Temporary logging added to help debug problem with zebedee auth being replaced by AWS auth in header  from Search API.
@rahulPalliyalil
> Add logs for debugging header problem

- errors/callback_stacktrace_test.go
- responder/responder.go
- responder/responder_test.go
Added small addtion to catch status code as 0 and return 500 in responder.Error.
This can happen if you're attempting to dynamically assert a status code and it returns a 0.
Check change makes sense, test passes.
Anyone
> return status 500 if pass as 0 in responder.Error

- http/client.go
- http/custom_roundtripper.go
It is needed to pass separate client objects to clienter default client and aws signer client, otherwise the transport of the aws signer will overwrite the default client. transport, which will cause signing when it tries to call even custom endpoints.
@cookel2
> Pass separate client objects for awsSigner and default http

- errors/callback.go
- errors/callback_test.go
- responder/responder.go
Add UnwrapErrorMessage function to complement ErrorMessage callback and implement in responder.
Previously the function for recovering an error message from an error would return the error message for the first error in the chain that has a Message() function, whether or not the message was a blank string or not. Now UnwrapErrorMessage will recursively unwrap the errors until it finds a non-empty string before it defaults to the error's default Error() string.
This brings the behaviour in line with the UnwrapStatusCode behavour and means an error message can be recovered from an error that was wrapped with a message several calls up the stack.
Anywhere relying on existing behaviour of ErrorMessage() should be unchanged.
Check change makes sense, tests pass
Anyone
> Add unwrap error message to callback and utilise in responder

- http/server.go
- http/server_test.go
- http/utils.go
Add an overall request timeout so that if a write timeout will be triggered, the request will be terminated as well, and a response written, before the writer is closed, since there is no value in continuing if the writer has been closed.
Review code
Anyone
> Add an overall request timeout

- go.mod
- http/server.go
- http/server_test.go
Add the timeout handler when performing the Server.ListenAndServe(), after the Server object has been created and the various timeout values, specifically the WriteTimeout, has been set by the client
Review code and tests
Anyone
> Fix for request timeout

- go.mod
dp-net v2.7.1, contains a change to add timeouts to the standard http server. However it adds this to every http server created rather than one with a non-standard timeout added.
Eyeball
dp developer
> fix - retract v2.7.1

- http/client.go
- http/client_test.go
- http/mock_client.go
- http/server.go
- http/server_test.go
Server:
1. Introduce a server-Constructor that takes in a timeout value  (current code uses the WriteTimeout as the execution timeout value, which is both incorrect and not configurable).
Client:
1. Introduce an "overall" timeout value (current timeout is wrongly named - as it is per try timeout value), will also rename the ambiguously named variables.
2. The overall timeout value will be set in the context.
Eyeball
Describe who worked on the changes, so that other people can review.
> dp-net timeout improvements

- responder/responder.go
dp-population-types-api-web has been seen to produce a stupidly long log line on a failure to write response of 1914357 bytes.
And such long log lines can cause logstash a bad day.
This change (once dp-population-types-api uses new version of this lib code) should fix that.
Do code changes make sense ?
Anyone
> Limit whats logged to a sensible amount on a write response failure

- go.mod
- go.sum
- http/client.go
This is being done as it should never have been removed (it was not realised by whoever reomoved it that its needed in dp-deployer). It's needed in dp-deployer to help fix audit failures.
Run tests
Anyone
> Add DefaultClient for dp-deployer

- links/links.go
- links/links_test.go
Added logic so that internal request links will be built with the same host as the request
required by ticket https://jira.ons.gov.uk/browse/DIS-1615
Check changes make sense
CI passes
Changes can be tested within dataset-catalogue stack by replacing dp-net with a local version
Anyone
> internal requests now use the incoming host to build links, tests added

- links/links.go
- links/links_test.go
Path-prefix is also included within internal links if present
check changes are ok
CI passes
Anyone
> builder uses path-prefix when available, tests fixed

- links/links.go
- links/links_test.go
External links are now found by checking for the `api` prefix for the host. Using incoming request host to build internal links
Check changes are ok
ci passes
All unit tests make sense, no missing cases
Anyone
> updated builder to better handle internal and external links

- links/links.go
- links/links_test.go
Download links are now built from the defaultURL provided. This means all download links will be external and there is no need for the builder to be created for downloads.
Check changes are ok
All unit test cases have been checked
Anyone
> rewrite download links using default external url

- links/links.go
- links/links_test.go
- Part of work required for https://officefornationalstatistics.atlassian.net/browse/DIS-3582
- Download links can be rewritten with or without the `/` prefix. (I have tested locally with the dataset-api)
- New function to remove specified prefix from path to simplify code
- Check changes are ok
Anyone
> reduce duplicate code and handle forward slash prefix
